# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"

  config.vm.provider :virtualbox do |v|
    v.memory = 521
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define :control do |control|
    control.vm.hostname = "btkien"
    control.vm.box = "geerlingguy/ubuntu1804"
    control.vm.box_check_update = false
    control.vm.synced_folder "data/", "/tmp/data",
      create: true, id: "data",
      owner: "root", "group": "root"
  end
end